version: "3.9"
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT_BACKEND}"
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      - mariadb

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "${DB_PORT_FRONTEND}"

  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT_MYSQL}"
    volumes:
      - mariadb_data:/var/lib/mysql

volumes:
  mariadb_data: